version: '3'

services:
  database:
    image: 'mysql:5.7'
    environment:
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
  application:
    depends_on:
      - database
    environment:
      DB_HOST: 'database'
      APP_DEBUG: 'true'
      APP_ENV: 'development'
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www

volumes:
  mysql:
