version: '3'

services:
  mariadb:
    image: 'bitnami/mysql:latest'
    environment:
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_DATABASE=$DB_DATABASE
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - mysql:/bitnami
    ports:
      - 3306:3306
  application:
    depends_on:
      - mariadb
    environment:
      DB_HOST: 'mariadb'
      APP_DEBUG: 'true'
      APP_ENV: 'development'
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www

volumes:
  mysql:
